-- Seed data_attributes with the full canonical list (public = true for dropdown/search).
-- Idempotent: only inserts when name + public does not already exist.

insert into public.data_attributes (name, public)
select v.name, true
from (values
  ('Latitude'),
  ('Longitude'),
  ('City Name'),
  ('Contact Last Name'),
  ('Contact First Name'),
  ('Country Code Alpha-2'),
  ('Country Code Alpha-3'),
  ('Email Address'),
  ('Address'),
  ('Phone Number'),
  ('Country Name'),
  ('Company Name'),
  ('State Name'),
  ('Language Name'),
  ('Contact Mobile Phone Number'),
  ('Postal Code'),
  ('County Name'),
  ('Latitude-Longitude'),
  ('MAID'),
  ('IPv4 Address'),
  ('Company Website'),
  ('Company Employee Count'),
  ('ZIP Code'),
  ('Company Industry'),
  ('Neighborhood Name'),
  ('Brand Name'),
  ('City District Name'),
  ('Website'),
  ('Contact Email Address'),
  ('IPv6 Address'),
  ('Contact Full Name'),
  ('Company Phone Number'),
  ('Contact Job Title'),
  ('Country Code Alpha-3'),
  ('Contact Gender'),
  ('Company Annual Revenue'),
  ('Contact LinkedIn'),
  ('State Abbreviation'),
  ('Stock Ticker'),
  ('Land Type'),
  ('Company Address'),
  ('Company Domain'),
  ('Land Zoning'),
  ('Company LinkedIn'),
  ('Job Title'),
  ('Company ID'),
  ('Contact Phone Number'),
  ('Company NAICS Code'),
  ('Company Email Address'),
  ('Opening Hours'),
  ('UID'),
  ('Location ID'),
  ('Contact Work Email Address'),
  ('Location Name'),
  ('Company SIC Code'),
  ('AAID'),
  ('URL'),
  ('Job Function'),
  ('Currency Code'),
  ('Area ID'),
  ('IP Address'),
  ('Company Description'),
  ('POI Telephone'),
  ('Fax Number'),
  ('Organization Type'),
  ('Hashed Email Address'),
  ('Contact Age'),
  ('Company Trade Name'),
  ('Province Name'),
  ('Small Area ID'),
  ('Company Legal Name'),
  ('Company NAICS Name'),
  ('Contact Facebook URL'),
  ('Job Description'),
  ('Organization Name'),
  ('Company SIC Name'),
  ('POI ID'),
  ('Placekey'),
  ('Job Source URL'),
  ('ISIN'),
  ('Brand ID'),
  ('Mobile Advertising ID (MAID) Type'),
  ('POI Category'),
  ('Product Name'),
  ('Job Level'),
  ('Job Remote'),
  ('VIN'),
  ('POI Sub-category'),
  ('Product Category'),
  ('Product Rating'),
  ('Job Compensation'),
  ('Job Type'),
  ('Job Source'),
  ('Product URL'),
  ('Product Price'),
  ('Contact Middle Name'),
  ('Job Name'),
  ('Product Description'),
  ('Currency Name'),
  ('Median Home Value'),
  ('Median Rent'),
  ('Price per Square Foot'),
  ('Property Tax Rate'),
  ('Property Tax Amount'),
  ('Owner Occupancy Rate'),
  ('Vacancy Rate'),
  ('Year Built'),
  ('Building Square Footage'),
  ('Lot Size'),
  ('Number of Bedrooms'),
  ('Number of Bathrooms'),
  ('HOA Fee'),
  ('Foreclosure Rate'),
  ('Housing Affordability Index'),
  ('Rental Yield'),
  ('Cap Rate'),
  ('Days on Market'),
  ('Building Type (SFH/Condo/Multi-family)'),
  ('Permit Activity Rate'),
  ('Average Annual Temperature'),
  ('Average Winter Temperature'),
  ('Average Summer Temperature'),
  ('Annual Precipitation'),
  ('Snowfall (Annual)'),
  ('Humidity (Average)'),
  ('UV Index'),
  ('Heatwave Days per Year'),
  ('Flood Risk Score'),
  ('Wildfire Risk Score'),
  ('Hurricane Risk Score'),
  ('Air Quality Index (AQI)'),
  ('PM2.5 Level'),
  ('CO2 Emissions per Capita'),
  ('Drought Severity Index'),
  ('Elevation'),
  ('Coastal Proximity'),
  ('Tree Canopy Coverage'),
  ('Water Quality Index'),
  ('Climate Resilience Score'),
  ('Life Expectancy'),
  ('Infant Mortality Rate'),
  ('Obesity Rate'),
  ('Diabetes Prevalence'),
  ('Smoking Rate'),
  ('Mental Health Distress Rate'),
  ('Uninsured Rate'),
  ('Primary Care Physicians'),
  ('Hospital Beds'),
  ('Health Expenditure per Capita'),
  ('Vaccination Rate'),
  ('Cancer Incidence Rate'),
  ('Opioid Overdose Rate'),
  ('Physical Activity Rate'),
  ('Food Insecurity Rate'),
  ('Access to Healthy Food Index'),
  ('Maternal Mortality Rate'),
  ('Health Disparity Index'),
  ('Disability Rate'),
  ('Emergency Response Time'),
  ('Median Household Income'),
  ('Per Capita Income'),
  ('Median Net Worth'),
  ('Mean Net Worth'),
  ('Wealth Gini Coefficient'),
  ('Homeownership Rate'),
  ('Retirement Account Participation Rate'),
  ('Median Retirement Balance'),
  ('Investment Account Ownership Rate'),
  ('Business Ownership Rate'),
  ('Debt-to-Income Ratio'),
  ('Student Loan Burden'),
  ('Mortgage Debt Rate'),
  ('Credit Card Debt Rate'),
  ('Bankruptcy Rate'),
  ('Savings Rate'),
  ('Asset Diversification Index'),
  ('Inherited Wealth Rate'),
  ('Trust Ownership Rate'),
  ('Financial Literacy Index'),
  ('Broadband Usage'),
  ('Fiber Coverage Rate'),
  ('5G Coverage Rate'),
  ('Average Internet Speed'),
  ('Smartphone Penetration Rate'),
  ('Computer Ownership Rate'),
  ('Cloud Adoption Rate (Business)'),
  ('Data Center Presence'),
  ('Startup Density'),
  ('Venture Capital Investment Volume'),
  ('Tech Workforce Share'),
  ('Patent Filings per Capita'),
  ('AI Adoption Rate'),
  ('Cybersecurity Incident Rate'),
  ('E-commerce Adoption Rate'),
  ('Digital Payment Adoption Rate'),
  ('Remote Work Rate'),
  ('IT Spending per Business'),
  ('Tech Industry Employment Share'),
  ('STEM Degree Rate'),
  ('Labor Force Participation Rate'),
  ('Unemployment Rate'),
  ('Underemployment Rate'),
  ('Median Wage'),
  ('Wage Growth Rate'),
  ('Industry Employment Mix'),
  ('Small Business Density'),
  ('Business Formation Rate'),
  ('Business Survival Rate (5-year)'),
  ('Minority-Owned Business Rate'),
  ('Women-Owned Business Rate'),
  ('Union Membership Rate'),
  ('Gig Worker Rate'),
  ('Self-Employment Rate'),
  ('Average Commute Time'),
  ('Job Growth Rate'),
  ('High-Skill Job Share'),
  ('Low-Wage Job Share'),
  ('Public Sector Employment Share'),
  ('Corporate Headquarters Count'),
  ('Total Population'),
  ('Population Density'),
  ('Population Growth Rate'),
  ('Median Age'),
  ('Age Distribution'),
  ('Gender Distribution'),
  ('Racial Composition'),
  ('Ethnic Composition'),
  ('Foreign-Born Population Rate'),
  ('Educational Attainment Rate'),
  ('High School Graduation Rate'),
  ('Bachelor''s Degree Rate'),
  ('Graduate Degree Rate'),
  ('Household Size (Average)'),
  ('Single-Parent Household Rate'),
  ('Marriage Rate'),
  ('Language Spoken at Home'),
  ('Religious Affiliation Distribution'),
  ('In-Migration Rate'),
  ('Out-Migration Rate'),
  ('Urban vs Rural Classification')
) as v(name)
where not exists (
  select 1 from public.data_attributes d where d.name = v.name and d.public = true
);
